Update to NG 6 and latest Ionic Store
natural-apptitude/ngrx-store-ionic-storage pull request #27
Opened 2018-09-28 15:55 UTC by vonboth

The imports of the RXJS library was outdated for the usage with NG 6

Updated the imports and changed the constants for the storage key to be a bit more generic.

Happy merging!

Thanks for your work

2018-10-10 14:25 UTC, joewoodhouse requested changes

2018-10-10 14:25 UTC, joewoodhouse commented on src/index.ts
> +  HYDRATED: 'APP_STATE_REHYDRATE'
Why did this change? It probably shouldn't be the case, but I've seen a few apps where they hardcode 'NSIS_APP_HYDRATED', so this will break them. Please revert unless there's a good reason.

2018-10-10 14:25 UTC, joewoodhouse commented on package.json
> +    "url": "git+https://github.com/vonboth/ngrx-store-ionic-storage.git"
Can you revert this back to the original pls.

2019-02-27 08:55 UTC, closed without merging

2019-02-27 08:56 UTC, vonboth commented
obsolete