Update README for ActionReducerMap
natural-apptitude/ngrx-store-ionic-storage pull request #6
Opened 2017-10-04 12:12 UTC by Biromain

Not probably the better way to get it, but without i cant `.select` hydrated without error.

2017-12-13 22:26 UTC, joewoodhouse commented on README.md
> +export interface State {}
Personal preference, but could you rename this to `HydratedState` so it doesn't have the same name as the state in the main reducer.

2017-12-13 22:27 UTC, joewoodhouse commented on README.md
> +    switch(action.type) {
Could we just remove the switch statement and `return state` ?

2017-12-13 22:27 UTC, joewoodhouse requested changes
Could you just update the 2 comments I put in, then will merge.

2017-12-14 17:57 UTC, Biromain commented
See #19 
This PR is orphan.

2017-12-14 17:57 UTC, closed without merging